sudo: false

language: cpp

addons_shortcuts:
  addons_clang38: &clang38
    apt:
      sources: [ 'ubuntu-toolchain-r-test', 'llvm-toolchain-precise', 'llvm-toolchain-precise-3.8' ]
      packages: [ 'clang-3.8' ]
  addons_gcc49: &gcc49
    apt:
      sources: [ 'ubuntu-toolchain-r-test' ]
      packages: [ 'g++-4.9' ]
  addons_gcc50: &gcc50
    apt:
      sources: [ 'ubuntu-toolchain-r-test' ]
      packages: [ 'g++-5' ]

matrix:
  include:
    - os: linux
      compiler: "clang3.8"
      env: COMPILER=clang++-3.8
      addons: *clang38
    - os: linux
      compiler: "gcc4.9"
      env: COMPILER=g++-4.9
      addons: *gcc49
    - os: linux
      compiler: "gcc5.0"
      env: COMPILER=g++-5
      addons: *gcc50

    - os: linux
      compiler: "coveralls"
      env: COMPILER=g++-5
      addons: *gcc50
      before_script: pip install --user cpp-coveralls
      after_success: coveralls --gcov gcov-5 --gcov-options '\-lp' --include source

script:
  - cmake --version
  - ./script/build &&
    ./script/run_tests
