sudo: false

language: cpp
compiler gcc

addons:
 apt:
   sources:
   - ubuntu-toolchain-r-test
   packages:
   - gcc-5.0
   - g++-5.0

script:
  - VERBOSE=1 CXX=${CPP} ./script/build &&
    ./script/run_tests
