sudo: false

language: cpp

matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5.2
      env: CPP=g++-5.2

script:
  - VERBOSE=1 CXX=${CPP} ./script/build &&
    ./script/run_tests
