sudo: false

language: cpp
compiler: gcc

addons:
 apt:
   sources:
   - llvm-toolchain-precise-3.8
   packages:
   - clang-3.8

script:
  - VERBOSE=1 CXX=${CPP} ./script/build &&
    ./script/run_tests
