#!/usr/bin/env bash

if [ ! -d build ]; then
  mkdir build
fi

cd build || exit 1

if [ "${1,,}" = "debug" ]; then
  cmake .. -G"Unix Makefiles" -DCMAKE_BUILD_TYPE=Debug
else
  cmake .. -G"Unix Makefiles"
fi
make
